import {defineTheme, token} from '@tileflow/core';

// Tileflow-owned semantic colors, calibrated from rendered Mapbox Standard
// default/day and default/night references on 2026-08-27. Standard is evergreen;
// this dated snapshot keeps our public themes deterministic.
/**
 * Streets' public visual vocabulary. Token IDs describe cartographic roles,
 * never physical layer IDs, so agents can edit the design without knowing the
 * compiler's layer topology.
 */
const streetsLightColors = {
  'boundaries.admin': '#D5A6AC',
  'boundaries.default': '#D5A6AC',
  'boundaries.disputed': '#D5A6AC',
  'boundaries.halo': '#F4F0EF',
  'boundaries.major': '#D5A6AC',
  'boundaries.maritime': '#648AA4',
  'boundaries.regional': '#C7B7B8',
  'buildings.active': '#EADFD5',
  'buildings.businessCorridor': '#F4E6D8',
  'buildings.businessCorridorOutline': '#DCCFC3',
  'buildings.civic': '#EFEBDF',
  'buildings.commercial': '#EFEBDF',
  'buildings.destination': '#EADFD5',
  'buildings.extrusion': '#E8E3DE',
  'buildings.fill': '#EFEBDF',
  'buildings.generic': '#EFEBDF',
  'buildings.industrial': '#EFEBDF',
  'buildings.outline': '#DDD4C4',
  'buildings.residential': '#EFEBDF',
  'buildings.shadow': '#ACA7A3',
  // Low-zoom bathymetry is composited over the ocean fill. These values are
  // deliberately pre-compensated so the rendered result, rather than the raw
  // paint token, matches Standard's more chromatic world-view water.
  'hydro.depth.m0': '#99DDFF59',
  'hydro.depth.m200': '#63C6FE59',
  'hydro.depth.m2000': '#0FB7FF59',
  'hydro.depth.m7000': '#0093F659',
  'hydro.ferry': '#5A88A9',
  'hydro.label': '#5A88A9',
  'hydro.ocean': '#99DDFF',
  'hydro.water': '#AEDBFC',
  'hydro.waterway': '#AEDBFC',
  'labels.country': '#5B5C5A',
  'labels.halo': '#F4F0EF',
  'labels.muted': '#777876',
  'labels.neighborhood': '#777876',
  'labels.overview': '#5B5C5A',
  'labels.poi': '#555654',
  'labels.primary': '#5B5C5A',
  'labels.road': '#505050',
  'labels.settlement': '#5B5C5A',
  'labels.shield.dark': '#1B1D27',
  'labels.shield.light': '#FFFFFF',
  'labels.strong': '#505050',
  'labels.water': '#5A88A9',
  'labels.waterHalo': 'rgba(244, 240, 239, 0.72)',
  'landcover.barren': '#F1EEE9',
  'landcover.farmland': '#E0ECD8',
  'landcover.flowerbed': '#BFE6AE',
  'landcover.global.barren': '#F2F0EB',
  'landcover.global.crop': '#D5EEC5',
  'landcover.global.grass': '#DFF1CF',
  'landcover.global.shrub': '#D8EFC8',
  'landcover.global.snow': '#F4F7F8',
  'landcover.global.trees': '#D0ECC3',
  'landcover.global.urban': '#F4F0EF',
  'landcover.grass': '#D9EBDD',
  'landcover.greenspace': '#C2E8B3',
  'landcover.greenspaceDark': '#B8E0AE',
  'landcover.ice': '#F4F7F8',
  'landcover.meadow': '#D9EBDD',
  'landcover.protected': '#D5E8D0',
  'landcover.recreationGround': '#C9E9BC',
  'landcover.rock': '#E9E8ED',
  'landcover.sand': '#F0ECC6',
  'landcover.scrub': '#D6E7D3',
  'landcover.urbanPark': '#C2E7B3',
  'landcover.villageGreen': '#C2E7B5',
  'landcover.wetland': '#D7E9DE',
  'landcover.wood': '#B7E2AC',
  'landuse.businessCorridor': '#F8EEE3',
  'landuse.businessCorridorOutline': '#E6D8CA',
  'landuse.cemetery': '#CCE5C6',
  'landuse.civic': '#F4F0EF',
  'landuse.commercial': '#F8EEE3',
  'landuse.education': '#EDE6D4',
  'landuse.government': '#F4F0EF',
  'landuse.industrial': '#E1E4F5',
  'landuse.medical': '#EEE0DF',
  'landuse.military': '#F4F0EF',
  'landuse.parking': '#E9E6E7',
  'landuse.parkingOutline': '#C8C8CF',
  'landuse.railway': '#E1E4F5',
  'landuse.recreation': '#C9E9BC',
  'landuse.recreationOutline': '#AED7A5',
  'landuse.residential': '#F4F0EF',
  'poi.arts-entertainment': '#B85CA4',
  'poi.education': '#777876',
  'poi.food-drink': '#D7892C',
  'poi.halo': '#FFFFFF',
  'poi.icon': '#777876',
  'poi.label': '#555654',
  'poi.landmark': '#B85CA4',
  'poi.lodging': '#806DC4',
  'poi.medical': '#C95E6B',
  'poi.park-nature': '#4C9478',
  'poi.public-services': '#777876',
  'poi.religion': '#B85CA4',
  'poi.retail': '#4C9478',
  'poi.sport-leisure': '#4C9478',
  'poi.transport': '#5C74D6',
  'poi.visitor-amenity': '#777876',
  'roads.bridge': '#C1C5D7',
  'roads.casing': '#A0ABC1',
  'roads.city.casing': '#E8E5E6',
  'roads.city.minor': '#CED0D8',
  'roads.city.primary': '#C2C6D0',
  'roads.city.secondary': '#C4C6CE',
  'roads.city.tertiary': '#C4C6CD',
  'roads.city.tunnel': '#E0E0E5',
  'roads.city.tunnelCasing': '#C5C5CF',
  'roads.cycleway': '#67AD73',
  'roads.default': '#C1C5D7',
  'roads.default.casing': '#A0ABC1',
  'roads.default.tunnel': '#DEE0E8',
  'roads.ferry': '#5A88A9',
  'roads.major': '#A6B1C2',
  'roads.minor': '#C1C5D7',
  'roads.motorway': '#A6B1C2',
  'roads.motorway.casing': '#8D9EAE',
  'roads.motorway.tunnel': '#D5DCE0',
  'roads.parkPath': '#D8E1D8',
  'roads.path': '#ECE9EB',
  'roads.path.casing': '#D2CED2',
  'roads.path.transition': '#F0EDEE',
  'roads.path.tunnel': '#E4E1E5',
  'roads.primary': '#C1C5D7',
  'roads.rail': '#8B8E99',
  'roads.railTransit': '#8E909D',
  'roads.secondary': '#C1C5D7',
  'roads.trunk': '#A5A7BF',
  'roads.trunk.casing': '#8F91AA',
  'roads.trunk.tunnel': '#C6C8D4',
  'roads.tunnel': '#DEE0E8',
  'surface.background': '#F4F0EF',
  'surface.building': '#EFEBDF',
  'surface.land': '#F4F0EF',
  'surface.park': '#B7E2AC',
  'surface.water': '#AEDBFC',
  'transit.primary': '#5C74D6',
  'vegetation.tree.bark': '#918878',
  'vegetation.tree.broadleaf.a': '#83AD83',
  'vegetation.tree.broadleaf.b': '#91BA8D',
  'vegetation.tree.broadleaf.c': '#A1C99B',
  'vegetation.tree.broadleaf.d': '#AFD4A7',
  'vegetation.tree.conifer.a': '#729B78',
  'vegetation.tree.conifer.b': '#81A880',
  'vegetation.tree.conifer.c': '#91B68B',
} as const;

const streetsDarkColors = {
  'boundaries.admin': '#9A6177',
  'boundaries.default': '#9A6177',
  'boundaries.disputed': '#9A6177',
  'boundaries.halo': '#252839',
  'boundaries.major': '#9A6177',
  'boundaries.maritime': '#8192B3',
  'boundaries.regional': '#76586D',
  'buildings.active': '#373743',
  'buildings.businessCorridor': '#45424E',
  'buildings.businessCorridorOutline': '#56515A',
  'buildings.civic': '#2C2E3D',
  'buildings.commercial': '#2C2E3D',
  'buildings.destination': '#3A3947',
  'buildings.extrusion': '#343646',
  'buildings.fill': '#2C2E3D',
  'buildings.generic': '#2C2E3D',
  'buildings.industrial': '#2C2E3D',
  'buildings.outline': '#3A3C49',
  'buildings.residential': '#2C2E3D',
  'buildings.shadow': '#121522',
  'hydro.depth.m0': '#13192FA8',
  'hydro.depth.m200': '#0F162CA8',
  'hydro.depth.m2000': '#0B1328A8',
  'hydro.depth.m7000': '#081022A8',
  'hydro.ferry': '#8799BE',
  'hydro.label': '#8799BE',
  'hydro.ocean': '#13192F',
  'hydro.water': '#18223B',
  'hydro.waterway': '#18223B',
  'labels.country': '#A6A7AC',
  'labels.halo': '#252839',
  'labels.muted': '#8F9098',
  'labels.neighborhood': '#8F9098',
  'labels.overview': '#B2B1B7',
  'labels.poi': '#B8B7BD',
  'labels.primary': '#A6A7AC',
  'labels.road': '#D0D0D6',
  'labels.settlement': '#A6A7AC',
  'labels.shield.dark': '#1B1D27',
  'labels.shield.light': '#FFFFFF',
  'labels.strong': '#D0D0D6',
  'labels.water': '#8799BE',
  'labels.waterHalo': 'rgba(37, 40, 57, 0.82)',
  'landcover.barren': '#303344',
  'landcover.farmland': '#3B4943',
  'landcover.flowerbed': '#4D5D54',
  'landcover.global.barren': '#303344',
  'landcover.global.crop': '#3B4943',
  'landcover.global.grass': '#3E4B47',
  'landcover.global.shrub': '#374440',
  'landcover.global.snow': '#3A4550',
  'landcover.global.trees': '#34453F',
  'landcover.global.urban': '#2D3043',
  'landcover.grass': '#3E4B47',
  'landcover.greenspace': '#4D5D54',
  'landcover.greenspaceDark': '#44504C',
  'landcover.ice': '#3A4550',
  'landcover.meadow': '#3E4B47',
  'landcover.protected': '#394842',
  'landcover.recreationGround': '#485650',
  'landcover.rock': '#343646',
  'landcover.sand': '#52503E',
  'landcover.scrub': '#374440',
  'landcover.urbanPark': '#4D5D54',
  'landcover.villageGreen': '#46564D',
  'landcover.wetland': '#33474A',
  'landcover.wood': '#34453F',
  'landuse.businessCorridor': '#45424E',
  'landuse.businessCorridorOutline': '#5A5561',
  'landuse.cemetery': '#45534D',
  'landuse.civic': '#2D3043',
  'landuse.commercial': '#45424E',
  'landuse.education': '#434247',
  'landuse.government': '#2D3043',
  'landuse.industrial': '#2A314B',
  'landuse.medical': '#453D48',
  'landuse.military': '#2D3043',
  'landuse.parking': '#393B49',
  'landuse.parkingOutline': '#555867',
  'landuse.railway': '#2A314B',
  'landuse.recreation': '#485650',
  'landuse.recreationOutline': '#63756A',
  'landuse.residential': '#2D3043',
  'poi.arts-entertainment': '#C786BC',
  'poi.education': '#8F9098',
  'poi.food-drink': '#D69A58',
  'poi.halo': '#252839',
  'poi.icon': '#8F9098',
  'poi.label': '#B8B7BD',
  'poi.landmark': '#C786BC',
  'poi.lodging': '#AA94DA',
  'poi.medical': '#DC7C89',
  'poi.park-nature': '#76B59A',
  'poi.public-services': '#8F9098',
  'poi.religion': '#C786BC',
  'poi.retail': '#76B59A',
  'poi.sport-leisure': '#76B59A',
  'poi.transport': '#8296E6',
  'poi.visitor-amenity': '#8F9098',
  'roads.bridge': '#636779',
  'roads.casing': '#454A59',
  'roads.city.casing': '#373B49',
  'roads.city.minor': '#4C505E',
  'roads.city.primary': '#636779',
  'roads.city.secondary': '#565A68',
  'roads.city.tertiary': '#505462',
  'roads.city.tunnel': '#464A57',
  'roads.city.tunnelCasing': '#393D4B',
  'roads.cycleway': '#5F9169',
  'roads.default': '#636779',
  'roads.default.casing': '#454A59',
  'roads.default.tunnel': '#525664',
  'roads.ferry': '#8799BE',
  'roads.major': '#70768A',
  'roads.minor': '#636779',
  'roads.motorway': '#70768A',
  'roads.motorway.casing': '#454A59',
  'roads.motorway.tunnel': '#5F6475',
  'roads.parkPath': '#4D5852',
  'roads.path': '#454956',
  'roads.path.casing': '#373A46',
  'roads.path.transition': '#4E5260',
  'roads.path.tunnel': '#3D414D',
  'roads.primary': '#636779',
  'roads.rail': '#7C7F8C',
  'roads.railTransit': '#777B89',
  'roads.secondary': '#636779',
  'roads.trunk': '#6F7188',
  'roads.trunk.casing': '#505264',
  'roads.trunk.tunnel': '#5B5D70',
  'roads.tunnel': '#525664',
  'surface.background': '#2D3043',
  'surface.building': '#2C2E3D',
  'surface.land': '#2D3043',
  'surface.park': '#34453F',
  'surface.water': '#18223B',
  'transit.primary': '#8296E6',
  'vegetation.tree.bark': '#52483D',
  'vegetation.tree.broadleaf.a': '#35473F',
  'vegetation.tree.broadleaf.b': '#3D5047',
  'vegetation.tree.broadleaf.c': '#45594E',
  'vegetation.tree.broadleaf.d': '#4D6255',
  'vegetation.tree.conifer.a': '#304139',
  'vegetation.tree.conifer.b': '#384A40',
  'vegetation.tree.conifer.c': '#405348',
} as const;

const streetsFonts = {
  default: 'Noto Sans Regular',
  places: 'Noto Sans Bold',
} as const;

const streetsImages = {
  'poi.arts-entertainment': 'culture',
  'poi.education': 'education',
  'poi.food-drink': 'food',
  'poi.landmark': 'culture',
  'poi.lodging': 'lodging',
  'poi.medical': 'health',
  'poi.park-nature': 'services',
  'poi.public-services': 'services',
  'poi.religion': 'culture',
  'poi.retail': 'shopping',
  'poi.sport-leisure': 'culture',
  'poi.transport': 'major-transit',
  'poi.visitor-amenity': 'services',
  'roads.crosswalk': 'crosswalk',
  'roads.oneway': 'oneway',
  'roads.shield.circleNeutral': 'road-shield-circle-neutral',
  'roads.shield.rectangleBlue': 'road-shield-rectangle-blue',
  'roads.shield.rectangleGreen': 'road-shield-rectangle-green',
  'roads.shield.rectangleNeutral': 'road-shield-rectangle-neutral',
  'roads.shield.rectangleOrange': 'road-shield-rectangle-orange',
  'roads.shield.rectangleRed': 'road-shield-rectangle-red',
  'roads.shield.rectangleYellow': 'road-shield-rectangle-yellow',
  'roads.sidewalkPattern': 'sidewalk-dot',
} as const;

export const streetsThemes = Object.freeze({
  light: defineTheme({
    id: 'streets-light',
    version: 1,
    colorScheme: 'light',
    tokens: {
      color: streetsLightColors,
      number: {},
      font: streetsFonts,
      image: streetsImages,
    },
    typography: {
      font: token.font('default'),
      places: {font: token.font('places')},
      poi: {font: token.font('default')},
      roads: {font: token.font('default')},
      water: {font: token.font('default')},
    },
    lighting: {
      anchor: 'viewport',
      color: '#FFFFFF',
      intensity: 0.15,
      position: [1.15, 210, 30],
    },
  }),
  dark: defineTheme({
    id: 'streets-dark',
    version: 1,
    colorScheme: 'dark',
    tokens: {
      color: streetsDarkColors,
      number: {},
      font: streetsFonts,
      image: {
        ...streetsImages,
        'roads.sidewalkPattern': 'sidewalk-dot-dark',
      },
    },
    typography: {
      font: token.font('default'),
      places: {font: token.font('places')},
      poi: {font: token.font('default')},
      roads: {font: token.font('default')},
      water: {font: token.font('default')},
    },
    lighting: {
      anchor: 'viewport',
      color: '#9FB6D0',
      intensity: 0.08,
      position: [1.15, 210, 30],
    },
  }),
});

/** Theme references consumed by the shared Streets module recipe. */
export const streetsVisual = {
  boundary: {
    admin: token.color('boundaries.admin'),
    halo: token.color('boundaries.halo'),
    regional: token.color('boundaries.regional'),
    overviewLabel: token.color('labels.overview'),
  },
  building: {
    extrusion: token.color('buildings.extrusion'),
    fill: token.color('buildings.fill'),
    outline: token.color('buildings.outline'),
    shadow: token.color('buildings.shadow'),
  },
  hydro: {
    depth0: token.color('hydro.depth.m0'),
    depth200: token.color('hydro.depth.m200'),
    depth2000: token.color('hydro.depth.m2000'),
    depth7000: token.color('hydro.depth.m7000'),
    ocean: token.color('hydro.ocean'),
    water: token.color('hydro.water'),
  },
  label: {
    country: token.color('labels.country'),
    halo: token.color('labels.halo'),
    muted: token.color('labels.muted'),
    neighborhood: token.color('labels.neighborhood'),
    overview: token.color('labels.overview'),
    poi: token.color('labels.poi'),
    primary: token.color('labels.primary'),
    road: token.color('labels.road'),
    settlement: token.color('labels.settlement'),
    shieldDark: token.color('labels.shield.dark'),
    shieldLight: token.color('labels.shield.light'),
    strong: token.color('labels.strong'),
    water: token.color('labels.water'),
    waterHalo: token.color('labels.waterHalo'),
  },
  landcover: Object.fromEntries(
    [
      'barren',
      'farmland',
      'flowerbed',
      'grass',
      'greenspace',
      'greenspaceDark',
      'ice',
      'meadow',
      'protected',
      'recreationGround',
      'rock',
      'sand',
      'scrub',
      'urbanPark',
      'villageGreen',
      'wetland',
      'wood',
    ].map((name) => [name, token.color(`landcover.${name}`)]),
  ),
  globalLandcover: Object.fromEntries(
    ['barren', 'crop', 'grass', 'shrub', 'snow', 'trees', 'urban'].map((name) => [
      name,
      token.color(`landcover.global.${name}`),
    ]),
  ),
  landuse: Object.fromEntries(
    [
      'businessCorridor',
      'businessCorridorOutline',
      'cemetery',
      'civic',
      'commercial',
      'education',
      'government',
      'industrial',
      'medical',
      'military',
      'parking',
      'parkingOutline',
      'railway',
      'recreation',
      'recreationOutline',
      'residential',
    ].map((name) => [name, token.color(`landuse.${name}`)]),
  ),
  poi: Object.fromEntries(
    [
      'arts-entertainment',
      'education',
      'food-drink',
      'halo',
      'icon',
      'label',
      'landmark',
      'lodging',
      'medical',
      'park-nature',
      'public-services',
      'religion',
      'retail',
      'sport-leisure',
      'transport',
      'visitor-amenity',
    ].map((name) => [name, token.color(`poi.${name}`)]),
  ),
  road: {
    casing: token.color('roads.default.casing'),
    cityCasing: token.color('roads.city.casing'),
    cityMinor: token.color('roads.city.minor'),
    cityPrimary: token.color('roads.city.primary'),
    citySecondary: token.color('roads.city.secondary'),
    cityTertiary: token.color('roads.city.tertiary'),
    cityTunnel: token.color('roads.city.tunnel'),
    cityTunnelCasing: token.color('roads.city.tunnelCasing'),
    cycleway: token.color('roads.cycleway'),
    default: token.color('roads.default'),
    ferry: token.color('roads.ferry'),
    motorway: token.color('roads.motorway'),
    motorwayCasing: token.color('roads.motorway.casing'),
    motorwayTunnel: token.color('roads.motorway.tunnel'),
    parkPath: token.color('roads.parkPath'),
    path: token.color('roads.path'),
    pathCasing: token.color('roads.path.casing'),
    pathTransition: token.color('roads.path.transition'),
    pathTunnel: token.color('roads.path.tunnel'),
    rail: token.color('roads.rail'),
    railTransit: token.color('roads.railTransit'),
    trunk: token.color('roads.trunk'),
    trunkCasing: token.color('roads.trunk.casing'),
    trunkTunnel: token.color('roads.trunk.tunnel'),
    tunnel: token.color('roads.default.tunnel'),
  },
  surface: {
    background: token.color('surface.background'),
    building: token.color('surface.building'),
    land: token.color('surface.land'),
    park: token.color('surface.park'),
    water: token.color('surface.water'),
  },
  transit: token.color('transit.primary'),
  tree: {
    bark: token.color('vegetation.tree.bark'),
    broadleaf: ['a', 'b', 'c', 'd'].map((suffix) =>
      token.color(`vegetation.tree.broadleaf.${suffix}`),
    ),
    conifer: ['a', 'b', 'c'].map((suffix) => token.color(`vegetation.tree.conifer.${suffix}`)),
  },
  image: {
    crosswalk: token.image('roads.crosswalk'),
    oneway: token.image('roads.oneway'),
    shieldCircleNeutral: token.image('roads.shield.circleNeutral'),
    shieldRectangleBlue: token.image('roads.shield.rectangleBlue'),
    shieldRectangleGreen: token.image('roads.shield.rectangleGreen'),
    shieldRectangleNeutral: token.image('roads.shield.rectangleNeutral'),
    shieldRectangleOrange: token.image('roads.shield.rectangleOrange'),
    shieldRectangleRed: token.image('roads.shield.rectangleRed'),
    shieldRectangleYellow: token.image('roads.shield.rectangleYellow'),
    sidewalkPattern: token.image('roads.sidewalkPattern'),
  },
  font: {
    default: token.font('default'),
    places: token.font('places'),
  },
} as const;
