import assert from 'node:assert/strict';
import {mkdir, mkdtemp, readFile, realpath, rm, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import {
  serializeTileflowIconsLockfile,
  sha256Hex,
  tileflowIconsLockfileName,
  type TileflowIconsLockfileV1,
} from '@tileflow/core';
import {linkWorkspacePackages} from '../../../test-support/workspace-packages';
import {createTileflowBuildArtifacts, getTileflowWatchPaths} from '../src/artifacts';
import {storeTileflowIconSetArtifact} from '../src/icon-cache';
import {compileTileflowIconPackages, prepareTileflowCatalogIcons} from '../src/icons';
import {lockFor, renderedIcon, setFixture} from './icon-set-fixtures';

const glyphs = `{kind:'url',url:'https://fonts.example.test/{fontstack}/{range}.pbf',fontStacks:['Noto Sans Regular','Noto Sans Bold']}`;
const unreferencedModules = `{poi:{type:'poi',icons:false},roads:disable()}`;
const shopSvg =
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><rect width="24" height="24" fill="#2563eb"/></svg>';

/** The exact generated identity of the local-only compatibility fixture before M5 wiring. */
const localOnlyContentHash = 'abfb41a715f1d8774a1639e1ff9117e3aef6aabeab7bdc9183715902fd98edf4';
/** Exact generated bytes recorded before shared composition became the normal path. */
const localOnlyFiles = [
  ['sprite.json', 61, '1af361c3761f1abd5129b110c0ee8179f52d470d7fc77f2e0298260755d38292'],
  ['sprite.png', 115, '967871e017018de42f317502c8585c9feeaf82189391dbcf951cd32cd17d60ce'],
  ['sprite@2x.json', 61, 'e107fdc44beca38f5f3035351a3ea3f2f38b9a70ff396e1d6ff3c3aba3631067'],
  ['sprite@2x.png', 146, '71e39842101b1b257babec5249e479c87d69ee00b29af0e0b54a1f4b639cef21'],
];

async function fixture(t: {after(callback: () => Promise<void>): void}, prefix: string) {
  const cwd = await mkdtemp(join(tmpdir(), prefix));
  await linkWorkspacePackages(cwd, ['core', 'maps']);
  t.after(() => rm(cwd, {force: true, recursive: true}));
  return cwd;
}

async function seedSharedFixture(cwd: string) {
  const brand = await setFixture(1, [
    renderedIcon('hospital', [255, 0, 0, 255]),
    renderedIcon('shop', [0, 255, 0, 255]),
  ]);
  const transport = await setFixture(2, [
    renderedIcon('hospital', [10, 20, 30, 120], 4, 8, [80, 90, 100, 220]),
    renderedIcon('bus', [0, 0, 255, 255]),
  ]);
  for (const set of [brand, transport])
    await storeTileflowIconSetArtifact(set.pin, set.artifact, {cacheRoot: cwd});
  await mkdir(join(cwd, 'icons'));
  await writeFile(join(cwd, 'icons', 'shop.svg'), shopSvg);
  await writeLock(cwd, lockFor({'@acme/brand': brand.pin, '@acme/transport': transport.pin}));
  await writeFile(
    join(cwd, 'tileflow.config.ts'),
    `import {defineMap, disable, iconSet} from '@tileflow/core';
import {streets} from '@tileflow/maps';
export default defineMap({id:'main',version:1,extends:streets,icons:[iconSet('@acme/brand'),iconSet('@acme/transport'),'./icons'],modules:${unreferencedModules},glyphs:${glyphs}});\n`,
  );
  return {brand, transport};
}

async function writeLock(cwd: string, lock: TileflowIconsLockfileV1) {
  await writeFile(join(cwd, tileflowIconsLockfileName), await serializeTileflowIconsLockfile(lock));
}

test('the normal artifact path composes two exact pins with a later local override', async (t) => {
  const cwd = await fixture(t, 'tileflow-icon-set-consumers-');
  const {brand, transport} = await seedSharedFixture(cwd);

  const plan = await createTileflowBuildArtifacts({
    assetBaseUrl: '/tileflow',
    cwd,
    icons: {cacheRoot: cwd, offline: true},
    styleBaseUrl: '/tileflow',
  });
  const entry = plan.buildManifest.maps.main!;
  const receipt = entry.sourceAssets.iconComposition;

  assert.equal(entry.mapRevisionSchemaVersion, 2);
  assert.ok(receipt);
  assert.deepEqual(
    receipt.contributors.map((contributor) =>
      contributor.kind === 'icon-set' ? contributor.reference : contributor.kind,
    ),
    ['@acme/brand', '@acme/transport', 'local'],
  );
  assert.deepEqual(
    receipt.winners.map((winner) => [winner.id, winner.contributor]),
    [
      ['bus', 1],
      ['hospital', 1],
      ['shop', 2],
    ],
  );
  assert.equal(
    receipt.contributors[0]!.kind === 'icon-set' && receipt.contributors[0]!.version,
    brand.pin.version,
  );
  assert.equal(
    receipt.contributors[1]!.kind === 'icon-set' && receipt.contributors[1]!.contentHash,
    transport.pin.contentHash,
  );
  assert.ok(plan.files.some((file) => file.fileName === 'icons/main/sprite.png'));
  assert.equal(JSON.stringify(receipt).includes(cwd), false);

  const realCwd = await realpath(cwd);
  assert.ok(plan.inputs.files.includes(join(realCwd, tileflowIconsLockfileName)));
  assert.ok(plan.inputs.directories.includes(join(realCwd, 'icons')));
  assert.ok(
    (await getTileflowWatchPaths({cwd})).includes(join(realCwd, tileflowIconsLockfileName)),
  );
});

test('a local-only map keeps its exact prior sprite bytes, manifest and content hash', async (t) => {
  const cwd = await fixture(t, 'tileflow-icon-set-local-only-');
  await mkdir(join(cwd, 'icons'));
  await writeFile(join(cwd, 'icons', 'shop.svg'), shopSvg);
  await writeFile(
    join(cwd, 'tileflow.config.ts'),
    `import {defineMap, disable} from '@tileflow/core';
import {streets} from '@tileflow/maps';
export default defineMap({id:'main',version:1,extends:streets,icons:['./icons'],modules:${unreferencedModules},glyphs:${glyphs}});\n`,
  );

  const plan = await createTileflowBuildArtifacts({assetBaseUrl: '/tileflow', cwd});
  const entry = plan.buildManifest.maps.main!;
  assert.equal(entry.mapRevisionSchemaVersion, undefined);
  assert.equal(entry.sourceAssets.iconComposition, undefined);
  assert.deepEqual(entry.sourceAssets.icons, [
    {
      format: 'svg',
      id: 'shop',
      kind: 'icon',
      sha256: await sha256Hex(await readFile(join(cwd, 'icons', 'shop.svg'))),
    },
  ]);

  const compiled = await compileTileflowIconPackages(plan.sourceProject, {cwd, target: 'local'});
  const iconPackage = compiled.packages[0]!;
  assert.equal(iconPackage.contentHash, localOnlyContentHash);
  assert.deepEqual(
    iconPackage.manifest.files.map((file) => [file.name, file.byteLength, file.sha256]),
    localOnlyFiles,
  );
  const prepared = await prepareTileflowCatalogIcons(plan.sourceProject, {
    assetBaseUrl: '/tileflow',
    baseDirectory: cwd,
    cwd,
  });
  assert.deepEqual(
    prepared.assets.map((asset) => asset.fileName),
    [
      'icons/main/sprite.json',
      'icons/main/sprite.png',
      'icons/main/sprite@2x.json',
      'icons/main/sprite@2x.png',
    ],
  );
});

test('an explicit offline cache miss never selects a different revision', async (t) => {
  const cwd = await fixture(t, 'tileflow-icon-set-offline-');
  await seedSharedFixture(cwd);
  const cacheRoot = await mkdtemp(join(tmpdir(), 'tileflow-icon-set-empty-cache-'));
  t.after(() => rm(cacheRoot, {force: true, recursive: true}));

  await assert.rejects(
    createTileflowBuildArtifacts({
      assetBaseUrl: '/tileflow',
      cwd,
      icons: {cacheRoot, offline: true},
      styleBaseUrl: '/tileflow',
    }),
    (error: unknown) => {
      assert.match(String(error), /offline|ICON_CACHE_MISS/u);
      return true;
    },
  );
});

test('the build never contacts an untrusted delivery origin for a locked artifact', async (t) => {
  const cwd = await fixture(t, 'tileflow-icon-set-origin-');
  await seedSharedFixture(cwd);
  const cacheRoot = await mkdtemp(join(tmpdir(), 'tileflow-icon-set-origin-cache-'));
  t.after(() => rm(cacheRoot, {force: true, recursive: true}));
  let requests = 0;

  await assert.rejects(
    createTileflowBuildArtifacts({
      assetBaseUrl: '/tileflow',
      cwd,
      icons: {
        cacheRoot,
        deliveryOrigins: ['https://cdn.example.test'],
        fetch: (async () => {
          requests += 1;
          return new Response(new Uint8Array(), {status: 200});
        }) as typeof globalThis.fetch,
      },
      styleBaseUrl: '/tileflow',
    }),
    /not trusted/u,
  );
  assert.equal(requests, 0);
});

test('an invalid lock fails the build without rewriting the executable config', async (t) => {
  const cwd = await fixture(t, 'tileflow-icon-set-invalid-lock-');
  await seedSharedFixture(cwd);
  const configPath = join(cwd, 'tileflow.config.ts');
  const before = await readFile(configPath, 'utf8');
  await writeFile(join(cwd, tileflowIconsLockfileName), '{"lockfileVersion":1,"sets":{}}\n');

  await assert.rejects(
    createTileflowBuildArtifacts({
      assetBaseUrl: '/tileflow',
      cwd,
      icons: {cacheRoot: cwd, offline: true},
      styleBaseUrl: '/tileflow',
    }),
    /lock|install/iu,
  );
  assert.equal(await readFile(configPath, 'utf8'), before);
});
