import {createHash} from 'node:crypto';
import type {TileflowVisualReviewDocument} from '@tileflow/capture';

export const tileflowVisualCompareReportSchemaVersion = 1 as const;
export const tileflowVisualCompareReportLimits = Object.freeze({
  maximumEmbeddedPngBytes: 64 * 1024 * 1024,
  maximumRows: 16,
  maximumTextLength: 320,
});

export type TileflowVisualCompareReportSide = {
  label: string;
  map: string;
  theme: string;
  png: Uint8Array;
};

export type TileflowVisualCompareReportRow = {
  cameraLabel: string;
  diffPng?: Uint8Array;
  left: TileflowVisualCompareReportSide;
  review: TileflowVisualReviewDocument;
  right: TileflowVisualCompareReportSide;
  zoom: number;
};

export type TileflowVisualCompareReportInput = {
  generatedBy: string;
  rows: readonly TileflowVisualCompareReportRow[];
  title: string;
};

/** Render one bounded, offline-only cartographic review document. */
export function renderTileflowVisualCompareReport(input: TileflowVisualCompareReportInput): string {
  if (input.rows.length === 0)
    throw new Error('A visual compare report requires at least one row.');
  if (input.rows.length > tileflowVisualCompareReportLimits.maximumRows) {
    throw new Error('The visual compare report exceeds the bounded row limit.');
  }
  assertBoundedText(input.generatedBy, 'generatedBy');
  assertBoundedText(input.title, 'title');
  const embeddedPngBytes = input.rows.reduce(
    (total, row) =>
      total + row.left.png.byteLength + row.right.png.byteLength + (row.diffPng?.byteLength ?? 0),
    0,
  );
  if (embeddedPngBytes > tileflowVisualCompareReportLimits.maximumEmbeddedPngBytes) {
    throw new Error('The visual compare report exceeds the bounded embedded PNG limit.');
  }
  const rows = [...input.rows].sort((left, right) => left.zoom - right.zoom);
  const seenZooms = new Set<number>();
  for (const row of rows) {
    if (!Number.isFinite(row.zoom) || row.zoom < 0 || row.zoom > 24 || seenZooms.has(row.zoom)) {
      throw new Error('Visual compare report zooms must be unique finite values from 0 to 24.');
    }
    seenZooms.add(row.zoom);
    for (const [field, value] of [
      ['cameraLabel', row.cameraLabel],
      ['left.label', row.left.label],
      ['left.map', row.left.map],
      ['left.theme', row.left.theme],
      ['right.label', row.right.label],
      ['right.map', row.right.map],
      ['right.theme', row.right.theme],
    ] as const) {
      assertBoundedText(value, field);
    }
  }
  const metadata = {
    schemaVersion: tileflowVisualCompareReportSchemaVersion,
    generatedBy: input.generatedBy,
    title: input.title,
    rows: rows.map(({cameraLabel, left, review, right, zoom}) => ({
      cameraLabel,
      left: {label: left.label, map: left.map, theme: left.theme},
      review,
      right: {label: right.label, map: right.map, theme: right.theme},
      zoom,
    })),
  };
  const rowHtml = rows.map((row, index) => renderRow(row, index)).join('\n');

  const script = reportScript();
  const scriptHash = createHash('sha256').update(script).digest('base64');
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'sha256-${scriptHash}'; base-uri 'none'; form-action 'none'; object-src 'none'" />
    <title>${escapeHtml(input.title)}</title>
    <style>${reportCss()}</style>
  </head>
  <body data-mode="side">
    <header class="toolbar">
      <div>
        <p class="eyebrow">Tileflow visual review</p>
        <h1>${escapeHtml(input.title)}</h1>
        <p>${rows.length} synchronized ${rows.length === 1 ? 'view' : 'views'} · informational comparison, never a baseline approval</p>
      </div>
      <div class="controls" role="group" aria-label="Comparison mode">
        <button type="button" data-mode="side" aria-pressed="true">Side by side <kbd>1</kbd></button>
        <button type="button" data-mode="wipe" aria-pressed="false">Wipe <kbd>2</kbd></button>
        <button type="button" data-mode="overlay" aria-pressed="false">Overlay <kbd>3</kbd></button>
        <button type="button" data-mode="blink" aria-pressed="false">Blink <kbd>4</kbd></button>
      </div>
      <label class="slider">Split <input id="split" type="range" min="0" max="100" value="50" /></label>
      <label class="slider">Opacity <input id="opacity" type="range" min="0" max="100" value="50" /></label>
    </header>
    <main>${rowHtml}</main>
    <footer>Generated by ${escapeHtml(input.generatedBy)}. All images and controls are embedded; this report performs no network requests.</footer>
    <script id="tileflow-review" type="application/json">${escapeJsonForHtml(metadata)}</script>
    <script>${script}</script>
  </body>
</html>\n`;
}

function renderRow(row: TileflowVisualCompareReportRow, index: number): string {
  const warnings = row.review.warnings ?? [];
  const status = reviewStatus(row.review);
  const metrics = row.review.exact
    ? `Exact: ${formatPercent(row.review.exact.ratio)} changed · ${
        row.review.perceptual
          ? `Perceptual: ${formatPercent(row.review.perceptual.ratio)} changed`
          : 'Perceptual: unavailable'
      }`
    : 'Pixel change metrics unavailable';
  const diff = row.diffPng
    ? `<details class="diff"><summary>Highlighted pixel diff</summary><img src="${pngDataUrl(row.diffPng)}" alt="Highlighted pixel difference at zoom ${escapeHtml(String(row.zoom))}" /></details>`
    : '';
  const warningHtml = warnings.length
    ? `<ul class="warnings">${warnings.map((warning) => `<li>${escapeHtml(warning)}</li>`).join('')}</ul>`
    : '';
  return `<section class="review-row" id="zoom-${safeFragment(row.zoom)}" data-row="${index}">
      <header class="row-header">
        <div><span class="zoom">z${escapeHtml(formatZoom(row.zoom))}</span><span>${escapeHtml(row.cameraLabel)}</span></div>
        <div><span class="status status-${status.kind}">${escapeHtml(status.label)}</span><span>${escapeHtml(metrics)}</span></div>
      </header>
      <div class="labels" aria-hidden="true"><strong>${escapeHtml(row.left.label)}</strong><strong>${escapeHtml(row.right.label)}</strong></div>
      <div class="stage" aria-label="${escapeHtml(row.left.label)} compared with ${escapeHtml(row.right.label)}">
        <figure class="pane pane-left"><img src="${pngDataUrl(row.left.png)}" alt="${escapeHtml(row.left.label)} at zoom ${escapeHtml(String(row.zoom))}" /><figcaption>${escapeHtml(row.left.map)} / ${escapeHtml(row.left.theme)}</figcaption></figure>
        <figure class="pane pane-right"><img src="${pngDataUrl(row.right.png)}" alt="${escapeHtml(row.right.label)} at zoom ${escapeHtml(String(row.zoom))}" /><figcaption>${escapeHtml(row.right.map)} / ${escapeHtml(row.right.theme)}</figcaption></figure>
      </div>
      ${warningHtml}
      ${diff}
      <details class="metadata"><summary>Identities and changed-pixel metrics</summary><pre>${escapeHtml(JSON.stringify(row.review, null, 2))}</pre></details>
    </section>`;
}

function reviewStatus(review: TileflowVisualReviewDocument): {kind: string; label: string} {
  if (!review.frameMatch) return {kind: 'error', label: 'Frame mismatch'};
  if (!review.dimensionsMatch) return {kind: 'error', label: 'Dimension mismatch'};
  if (!review.rendererMatch) return {kind: 'warn', label: 'Runtime mismatch'};
  if (!review.dataMatch) return {kind: 'warn', label: 'Data mismatch'};
  return {kind: 'ok', label: 'Comparable'};
}

function pngDataUrl(png: Uint8Array): string {
  return `data:image/png;base64,${Buffer.from(png).toString('base64')}`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function escapeJsonForHtml(value: unknown): string {
  return JSON.stringify(value)
    .replaceAll('&', '\\u0026')
    .replaceAll('<', '\\u003c')
    .replaceAll('>', '\\u003e')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}

function safeFragment(zoom: number): string {
  return String(zoom).replace('.', '-');
}

function formatZoom(zoom: number): string {
  return Number.isInteger(zoom) ? String(zoom) : String(zoom).replace(/0+$/u, '');
}

function formatPercent(ratio: number): string {
  return `${Math.round(ratio * 10_000) / 100}%`;
}

function reportCss(): string {
  return `:root{color-scheme:light;--ink:#20221f;--muted:#656961;--paper:#f6f3ea;--panel:#fffdf7;--line:#d8d3c6;--accent:#315d4d;--warn:#9a5b12;--error:#9b2c2c}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.toolbar{position:sticky;top:0;z-index:20;display:grid;grid-template-columns:minmax(240px,1fr) auto auto auto;gap:16px;align-items:end;padding:18px 24px;border-bottom:1px solid var(--line);background:rgba(246,243,234,.96);backdrop-filter:blur(12px)}h1{margin:0;font:650 24px/1.15 ui-serif,Georgia,serif}.toolbar p{margin:4px 0 0;color:var(--muted)}.eyebrow{font-size:11px!important;font-weight:750;letter-spacing:.12em;text-transform:uppercase;color:var(--accent)!important}.controls{display:flex;flex-wrap:wrap;gap:6px}.controls button{border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--ink);padding:7px 9px;cursor:pointer}.controls button[aria-pressed=true]{background:var(--accent);border-color:var(--accent);color:white}.controls button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #65a98f;outline-offset:2px}kbd{font:10px ui-monospace,monospace;opacity:.7}.slider{display:grid;gap:4px;color:var(--muted);font-size:11px}.slider input{width:116px}main{width:min(1600px,100%);margin:0 auto;padding:24px;display:grid;gap:24px}.review-row{border:1px solid var(--line);border-radius:12px;background:var(--panel);padding:14px;box-shadow:0 8px 26px rgba(42,39,31,.05)}.row-header,.labels{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:10px;color:var(--muted)}.row-header>div{display:flex;gap:10px;align-items:center}.zoom{border-radius:999px;background:#e3ece7;color:var(--accent);font-weight:750;padding:3px 9px}.status{border-radius:999px;padding:3px 8px;font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.04em}.status-ok{background:#dceee4;color:#225940}.status-warn{background:#fae8c5;color:var(--warn)}.status-error{background:#f5dada;color:var(--error)}.stage{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:2px;overflow:hidden;border-radius:8px;background:#252823;isolation:isolate}.pane{min-width:0;margin:0;position:relative;background:#ddd}.pane img{display:block;width:100%;height:auto}.pane figcaption{position:absolute;left:8px;bottom:8px;border-radius:5px;background:rgba(20,22,19,.78);color:white;padding:3px 7px;font-size:11px}.warnings{margin:12px 0 0;padding:10px 10px 10px 30px;border-radius:7px;background:#fff2d9;color:#75440b}.metadata,.diff{margin-top:10px}.metadata pre{overflow:auto;max-height:360px;padding:12px;border-radius:7px;background:#20231f;color:#e8eee8;font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}.diff img{display:block;max-width:100%;margin-top:8px;background:repeating-conic-gradient(#eee 0 25%,#fff 0 50%) 50%/18px 18px}summary{cursor:pointer;font-weight:650}body[data-mode=wipe] .stage,body[data-mode=overlay] .stage,body[data-mode=blink] .stage{display:block}.stage .pane-right{--split:50%;--opacity:.5}body[data-mode=wipe] .pane-right,body[data-mode=overlay] .pane-right,body[data-mode=blink] .pane-right{position:absolute;inset:0}body[data-mode=wipe] .pane-right{clip-path:inset(0 0 0 var(--split))}body[data-mode=overlay] .pane-right{opacity:var(--opacity)}body[data-mode=blink] .pane-right{opacity:var(--blink-opacity,1)}footer{padding:18px 24px;border-top:1px solid var(--line);color:var(--muted);text-align:center}@media(max-width:900px){.toolbar{position:static;grid-template-columns:1fr}.slider input{width:100%}.labels{display:none}body[data-mode=side] .stage{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}`;
}

function reportScript(): string {
  return `(()=>{const body=document.body;const buttons=[...document.querySelectorAll('button[data-mode]')];const split=document.getElementById('split');const opacity=document.getElementById('opacity');let blink=null;const panes=()=>document.querySelectorAll('.pane-right');const stopBlink=()=>{if(blink!==null){clearInterval(blink);blink=null;}panes().forEach((pane)=>pane.style.removeProperty('--blink-opacity'));};const applyValues=()=>{panes().forEach((pane)=>{pane.style.setProperty('--split',split.value+'%');pane.style.setProperty('--opacity',String(Number(opacity.value)/100));});};const setMode=(mode)=>{if(!['side','wipe','overlay','blink'].includes(mode))return;stopBlink();body.dataset.mode=mode;buttons.forEach((button)=>button.setAttribute('aria-pressed',String(button.dataset.mode===mode)));if(mode==='blink'&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let visible=true;blink=setInterval(()=>{visible=!visible;panes().forEach((pane)=>pane.style.setProperty('--blink-opacity',visible?'1':'0'));},700);}};buttons.forEach((button)=>button.addEventListener('click',()=>setMode(button.dataset.mode)));split.addEventListener('input',applyValues);opacity.addEventListener('input',applyValues);document.addEventListener('keydown',(event)=>{if(event.target instanceof HTMLInputElement)return;const modes={1:'side',2:'wipe',3:'overlay',4:'blink'};if(modes[event.key])setMode(modes[event.key]);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopBlink();else if(body.dataset.mode==='blink')setMode('blink');});applyValues();})();`;
}

function assertBoundedText(value: string, field: string): void {
  if (
    value.length < 1 ||
    value.length > tileflowVisualCompareReportLimits.maximumTextLength ||
    [...value].some((character) => {
      const codePoint = character.codePointAt(0)!;
      return codePoint <= 31 || codePoint === 127;
    })
  ) {
    throw new Error(`Visual compare report ${field} is invalid or exceeds its text limit.`);
  }
}
