import {constants} from 'node:fs';
import {lstat, mkdir, mkdtemp, open, readdir, realpath, rename, rm} from 'node:fs/promises';
import {homedir, platform} from 'node:os';
import {join, resolve} from 'node:path';
import {TileflowIconSetError, tileflowIconSetPinSchema, type TileflowIconSetPin} from '@tileflow/core';
import {verifyTileflowIconArtifact, type VerifiedTileflowIconArtifact} from './icon-artifact';
import type {CompiledTileflowIconPackage, CompiledTileflowIconPackageFile} from './icons';

export type TileflowIconCacheOptions = {
	/** Parent of the versioned tileflow/icons/v1 cache, not a serialized lock setting. */
	cacheRoot?: string;
	offline?: boolean;
	/** Trusted application configuration. A lock cannot extend this allowlist. */
	deliveryOrigins?: readonly string[];
	fetch?: typeof globalThis.fetch;
	signal?: AbortSignal;
};

export function getTileflowIconCacheDirectory(options: Pick<TileflowIconCacheOptions, 'cacheRoot'> = {}): string {
	const defaultRoot = platform() === 'darwin' ? join(homedir(), 'Library', 'Caches') : platform() === 'win32' ? process.env.LOCALAPPDATA ?? join(homedir(), 'AppData', 'Local') : process.env.XDG_CACHE_HOME ?? join(homedir(), '.cache');
	return join(resolve(options.cacheRoot ?? process.env.TILEFLOW_ICON_CACHE_DIR ?? defaultRoot), 'tileflow', 'icons', 'v1');
}

/** Read and verify an exact pin; a cache miss never resolves a newer version. */
export async function loadTileflowIconSetArtifact(input: TileflowIconSetPin, options: TileflowIconCacheOptions = {}): Promise<VerifiedTileflowIconArtifact> {
	const pin = tileflowIconSetPinSchema.parse(input);
	let cacheFailure: unknown;
	try {
		return await readCached(pin, options);
	} catch (cause) {
		if (cause instanceof TileflowIconSetError && cause.code === 'ICON_CACHE_UNSAFE') throw cause;
		cacheFailure = cause;
	}
	if (options.offline) {
		throw new TileflowIconSetError(isMissing(cacheFailure) ? 'ICON_CACHE_MISS' : 'ICON_PACKAGE_INTEGRITY', 'The exact verified icon artifact is unavailable offline; hydrate this pin explicitly', {cause: cacheFailure});
	}
	const url = new URL(pin.spriteUrl);
	const allowed = options.deliveryOrigins ?? ['https://api.tileflow.dev'];
	if (!allowed.some((origin) => origin === url.origin && new URL(origin).href === `${origin}/`)) {
		throw new TileflowIconSetError('ICON_DOWNLOAD_FAILED', 'Icon artifact delivery origin is not trusted');
	}
	const files: CompiledTileflowIconPackageFile[] = [];
	const signal = options.signal ? AbortSignal.any([options.signal, AbortSignal.timeout(30_000)]) : AbortSignal.timeout(30_000);
	try {
		for (const expected of pin.manifest.files) {
			signal.throwIfAborted();
			const fileUrl = `${pin.spriteUrl}${expected.name.slice('sprite'.length)}`;
			const response = await (options.fetch ?? globalThis.fetch)(fileUrl, {method: 'GET', credentials: 'omit', redirect: 'error', headers: {Accept: expected.contentType}, signal});
			if (response.status !== 200 || response.redirected || (response.url && response.url !== fileUrl) || !response.body) throw new Error('Unexpected artifact response');
			const type = response.headers.get('content-type')?.split(';')[0]?.trim().toLowerCase();
			const length = response.headers.get('content-length');
			if (type !== expected.contentType || (length !== null && (!/^\d+$/u.test(length) || Number(length) !== expected.byteLength))) {
				await response.body.cancel();
				throw new Error('Artifact response headers do not match the manifest');
			}
			const reader = response.body.getReader();
			const source = new Uint8Array(expected.byteLength);
			let offset = 0;
			try {
				while (true) {
					const chunk = await reader.read();
					if (chunk.done) break;
					if (offset + chunk.value.byteLength > source.byteLength) throw new Error('Artifact response exceeds its exact byte length');
					source.set(chunk.value, offset);
					offset += chunk.value.byteLength;
				}
				if (offset !== source.byteLength) throw new Error('Artifact response was truncated');
			} catch (cause) {
				await reader.cancel().catch(() => undefined);
				throw cause;
			} finally { reader.releaseLock(); }
			files.push({fileName: expected.name, contentType: expected.contentType, source});
		}
	} catch (cause) {
		throw new TileflowIconSetError('ICON_DOWNLOAD_FAILED', 'Exact icon artifact download failed', {cause});
	}
	return storeTileflowIconSetArtifact(pin, {contentHash: pin.contentHash, manifest: pin.manifest, files}, options);
}

/** Seed or repair a disposable cache using verified generated bytes, never original artwork. */
export async function storeTileflowIconSetArtifact(input: TileflowIconSetPin, artifact: CompiledTileflowIconPackage, options: Pick<TileflowIconCacheOptions, 'cacheRoot'> = {}): Promise<VerifiedTileflowIconArtifact> {
	const pin = tileflowIconSetPinSchema.parse(input);
	if (artifact.contentHash !== pin.contentHash) throw new TileflowIconSetError('ICON_PACKAGE_INTEGRITY', 'Artifact does not match the selected pin');
	const verified = await verifyTileflowIconArtifact({contentHash: pin.contentHash, manifest: pin.manifest, files: artifact.files});
	const root = await safeCacheRoot(options, true);
	const target = join(root, pin.contentHash);
	const temporary = await mkdtemp(join(root, `.incoming-${pin.contentHash}-`));
	try {
		for (const file of verified.package.files) {
			const handle = await open(join(temporary, file.fileName), 'wx', 0o600);
			try { await handle.writeFile(file.source); await handle.sync(); } finally { await handle.close(); }
		}
		for (let attempt = 0; attempt < 8; attempt += 1) {
			try { await rename(temporary, target); return verified; }
			catch (cause) { if (!hasCode(cause, 'EEXIST') && !hasCode(cause, 'ENOTEMPTY') && !hasCode(cause, 'EPERM')) throw cause; }
			try { return await readCached(pin, options); }
			catch (cause) { if (cause instanceof TileflowIconSetError && cause.code === 'ICON_CACHE_UNSAFE') throw cause; }
			// Retire only this validated hash directory. Never mutate files in a published cache entry.
			try {
				await assertDirectory(target);
				const retired = await mkdtemp(join(root, `.retired-${pin.contentHash}-`));
				try { await rename(target, join(retired, 'entry')); }
				catch (cause) { if (!isMissing(cause)) throw cause; }
				finally { await rm(retired, {recursive: true, force: true}); }
			} catch (cause) { if (!isMissing(cause)) throw cause; }
		}
		throw new TileflowIconSetError('ICON_CACHE_UNSAFE', 'Concurrent cache repairs did not converge; retry this exact pin');
	} finally { await rm(temporary, {recursive: true, force: true}); }
}

async function readCached(pin: TileflowIconSetPin, options: Pick<TileflowIconCacheOptions, 'cacheRoot'>): Promise<VerifiedTileflowIconArtifact> {
	const root = await safeCacheRoot(options, false);
	const directory = join(root, pin.contentHash);
	await assertDirectory(directory);
	const entries = (await readdir(directory)).sort();
	const expectedNames = pin.manifest.files.map((file) => file.name).sort();
	if (entries.length !== 4 || entries.some((name, index) => name !== expectedNames[index])) throw new TileflowIconSetError('ICON_PACKAGE_INTEGRITY', 'Cache entry does not contain exactly four generated files');
	const files: CompiledTileflowIconPackageFile[] = [];
	for (const expected of pin.manifest.files) {
		files.push({fileName: expected.name, contentType: expected.contentType, source: await readSafeFile(join(directory, expected.name), expected.byteLength)});
	}
	return verifyTileflowIconArtifact({contentHash: pin.contentHash, manifest: pin.manifest, files});
}

async function safeCacheRoot(options: Pick<TileflowIconCacheOptions, 'cacheRoot'>, create: boolean): Promise<string> {
	const root = getTileflowIconCacheDirectory(options);
	// System ancestors may be canonical OS symlinks; application cache entries may not be symlinks.
	const base = resolve(root, '..', '..', '..');
	if (create) await mkdir(base, {recursive: true, mode: 0o700});
	await assertDirectory(base);
	let current = await realpath(base);
	for (const segment of ['tileflow', 'icons', 'v1']) {
		current = join(current, segment);
		if (create) await mkdir(current, {mode: 0o700}).catch((cause: unknown) => { if (!hasCode(cause, 'EEXIST')) throw cause; });
		await assertDirectory(current);
	}
	return current;
}

async function assertDirectory(path: string): Promise<void> {
	const entry = await lstat(path);
	if (!entry.isDirectory() || entry.isSymbolicLink()) throw new TileflowIconSetError('ICON_CACHE_UNSAFE', 'Icon cache paths must be directories, not symlinks');
}

export async function readSafeFile(path: string, maximumBytes: number, exact = true): Promise<Uint8Array> {
	const entry = await lstat(path);
	if (!entry.isFile() || entry.isSymbolicLink()) throw new TileflowIconSetError('ICON_CACHE_UNSAFE', 'Icon files must be regular files, not symlinks');
	const handle = await open(path, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
	try {
		const opened = await handle.stat();
		if (!opened.isFile() || opened.ino !== entry.ino || opened.dev !== entry.dev || opened.size > maximumBytes || (exact && opened.size !== maximumBytes)) throw new TileflowIconSetError('ICON_PACKAGE_INTEGRITY', 'Icon file size or identity changed');
		const buffer = new Uint8Array(maximumBytes + 1);
		let offset = 0;
		while (offset < buffer.length) {
			const {bytesRead} = await handle.read(buffer, offset, buffer.length - offset, null);
			if (bytesRead === 0) break;
			offset += bytesRead;
		}
		if (offset > maximumBytes || (exact && offset !== maximumBytes)) throw new TileflowIconSetError('ICON_PACKAGE_INTEGRITY', 'Icon file byte length changed');
		return buffer.slice(0, offset);
	} finally { await handle.close(); }
}

function hasCode(error: unknown, code: string): boolean { return error !== null && typeof error === 'object' && 'code' in error && error.code === code; }
function isMissing(error: unknown): boolean { return hasCode(error, 'ENOENT'); }
